version: '3'

services: 

  app: 
    build:
        context: node
    container_name: app
    # entrypoint: dockerize -wait tcp://database:3306 -timeout 50s docker-entrypoint.sh
    command: bash -c "npm install && node index.js"
    networks:
        - node-network
    volumes:
      - ./node:/usr/src/app
    tty: true
    depends_on:
      - db

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - "8080:80"
    volumes:
      - ./nginx:/home/desenv/dockerfullcicle/nginx
      - ./nginx:/etc/nginx/conf.d  
    depends_on:
      - app
      - db
    networks:
      - node-network

  db:
      image: mysql:5.7
      command: --innodb-use-native-aio=0
      container_name: db
      restart: always
      tty: true
      volumes:
        - ./mysql:/var/lib/mysql
      environment: 
        - MYSQL_DATABASE=nodedb
        - MYSQL_ROOT_PASSWORD=root
      networks:
        - node-network
networks:
  node-network:
    driver: bridge
